echo 'AT+GOOGSETNV="UECAPA_PHY_UE_TX_ANTENNASEL_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_PHY_UE_SPECIFIC_REF_SIG_SUPPORT",0,"01"\r
AT+GOOGSETNV="!LTEL3.LTERRC_LOGGED_MEAS",0,"01"\r
AT+GOOGSETNV="NR.CONFIG.MODE",0,"11"\r
AT+GOOGSETNV="DS.NR.CONFIG.MODE",0,"11"\r
AT+GOOGSETNV="!NRCAPA.Gen.SrsTxSwitch",0,"01"\r
AT+GOOGSETNV="!SAEL3.NR_QRB_MODE_UPDATE_SUPPORT",0,"01"\r
' > /dev/umts_router & cat /dev/umts_router 