echo 'AT+GOOGSETNV="UECAPA_REL10_SIMUL_PUCCH_PUSCH",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_CROSS_CA_SCHEDULING",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_PMI_DISABLING",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_TM5_FDD",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_TM5_TDD",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_MULTI_CLUSTER_PUSCH_WITHIN_CC",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_NON_CONTIG_UL_RA_WITH_CC",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_TM9_WITH_8TX",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_TM9TM10_SETLAYER",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_LOGGED_MEAS_IDLE",0,"01"\r
AT+GOOGSETNV="UECAPA_REL10_STAND_ALONE_GNSS",0,"01"\r
' > /dev/umts_router & cat /dev/umts_router 