echo 'AT+GOOGSETNV="UECAPA_REL15_FSULPCC_1_256Q",0,"01"\r
AT+GOOGSETNV="UECAPA_REL15_FSULPCC_2_256Q",0,"01"\r
AT+GOOGSETNV="UECAPA_REL15_CA_IDLE_MODE_MEAS_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL15_CA_IDLE_MODE_VALIDITY_AREA_SUPPORT",0,"01"\r
' > /dev/umts_router & cat /dev/umts_router 