echo 'AT+GOOGSETNV="UECAPA_REL12_EXTENDED_RLC_LI_FIELD_R12_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_CSI_RS_DISCOVERY_SIGNALS_MEAS_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_EXTENDED_RSRQ_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_EXTENDED_MAX_MEASID_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_INC_MON_UTRA_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_INC_MON_EUTRA_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_ALTERNATIVE_TTT_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_TIMER_T312_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_DISCOVERY_SIGNALS_IN_DEACT_SCELL_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_NRR_FOR_TTI_B_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_PUSCH_FEEDBACK_MODE_R12_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_ENHANCED_4TX_CODEBOOK_R12_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_EHARQ_PATTERN_FDD_SUPPORT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL12_ALTERNATIVE_TBS_INDICES_R12_SUPPORT",0,"01"\r
' > /dev/umts_router & cat /dev/umts_router 