echo 'AT+GOOGSETNV="UECAPA_REL11_INTERBANDTDD_CA_WITHDIFFCONFIG",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_UE_RX_TXTIMEDIFFMEAS",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_POWERPREFIND",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_UL_COMP",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_TXDIV_PUCCH1B_CHSELECT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_TDD_SPECIALSUBFRAME",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_SS_CCH_INTERFHANDL",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_MULTIACK_CSI_REPORTING",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_CRS_INTERFHANDL",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_SUPP_ROHC_CONT",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_PDCP_SN_EXTENSION",0,"01"\r
AT+GOOGSETNV="UECAPA_REL11_EPDCCH",0,"01"\r
' > /dev/umts_router & cat /dev/umts_router 